In [1]:
import numpy as np
import operator
# import KNN_filematrix as KNN

In [7]:
# dataData,dataLabels = KNN.filematrix('datingTestSet2.txt')

In [8]:
def autoNorm(dataSet):
    minVals = dataSet.min(0)
    maxVals = dataSet.max(0)
    ranges = maxVals - minVals
    normDataSet = np.zeros(np.shape(dataSet))
    m = dataSet.shape[0]
    normDataSet = dataSet - np.tile(minVals,(m,1))#把minVals复制m次，和dataSet里面对应元素相减
    normDataSet = normDataSet/np.tile(ranges,(m,1))
    return normDataSet,ranges,minVals

In [9]:
# normDataSet,ranges,minVals = autoNorm(dataData)
# print(normDataSet)

[[0.44832535 0.39805139 0.56233353]
 [0.15873259 0.34195467 0.98724416]
 [0.28542943 0.06892523 0.47449629]
 ...
 [0.29115949 0.50910294 0.51079493]
 [0.52711097 0.43665451 0.4290048 ]
 [0.47940793 0.3768091  0.78571804]]


In [10]:
print(ranges)

[9.1273000e+04 2.0919349e+01 1.6943610e+00]


In [11]:
print(minVals)

[0.       0.       0.001156]
