In [13]:
import numpy as np
import operator
from KNN_filematrix import filematrix
from KNN_na import autoNorm
from KNN_classify import classify
# import KNN_filematrix as filematrix 
# import KNN_na as autoNorm
# import KNN_classify as classify0
#如果是下方这种导入方式，就要写成autoNorm.autoNorm的形式（模块.函数名）

In [27]:
def datingClassTest():
    hoRatio = 0.1  #用整个数据的百分之多少来进行测试
    datingDataMat,datingLabels = filematrix('datingTestSet2.txt')#读取数据
    normMat,ranges,minVals = autoNorm(datingDataMat)#读取处理好的特征矩阵
    m = normMat.shape[0]#得到特征矩阵的行数
    print(m)
    numTestVecs = int(m*hoRatio)#用来测试的特征矩阵的行数
    print(normMat)
    print(np.shape(normMat))
    errorCount = 0.0
    for i in range(numTestVecs):
        classifierResult = classify(normMat[i, :], normMat[numTestVecs:m, :], datingLabels[numTestVecs:m], 3)
        #利用前numTestVecs行数据进行测试，利用从numTestVecs行数据进行测试到m行数据进行测试
        #classify(inX,dataSet,labels,k)
        print("the classifier came back with: %d, the real answer is: %d" % (classifierResult, datingLabels[i]))
        if (classifierResult != datingLabels[i]): errorCount += 1.0 
            #如果预测结果和真实结果不一样，就在错误个数上加1
    print("the total error rate is: %f" % (errorCount / float(numTestVecs)))
    print(errorCount)


In [28]:
datingClassTest()

1000
[[0.44832535 0.39805139 0.56233353]
 [0.15873259 0.34195467 0.98724416]
 [0.28542943 0.06892523 0.47449629]
 ...
 [0.29115949 0.50910294 0.51079493]
 [0.52711097 0.43665451 0.4290048 ]
 [0.47940793 0.3768091  0.78571804]]
(1000, 3)
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 2, the real answer is: 2
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 2, the real answer is: 2
the classifier came back with: 1, t